### ISSUE TITLE
iban elfproef

### ISSUE THREAD

**Issue by jvanbaarsen** [sytzeloor/elfproef#4]
Hello,

Are there any plans on implementing the elfproef for the new sepa rules?

**Comment by ariejan** [comment]
There is now.

For future reference: http://nl.wikipedia.org/wiki/International_Bank_Account_Number

**Comment by jvanbaarsen** [comment]
@ariejan You mean the current system already supports the IBAN? Since i didn't see any specific tests or code for it?

**Comment by ariejan** [comment]
@jvanbaarsen No, there are plans now ;-)

**Comment by jvanbaarsen** [comment]
@ariejan if you want, i can create it?

**Comment by ariejan** [comment]
Go right ahead. Looking forward to your pull request.

**Comment by jvanbaarsen** [comment]
see: https://github.com/sytzeloor/elfproef/pull/5
